From NoReply Mon Mar  9 15:08:38 2009
X-Apparently-To: postmaster@yahoo.com via 68.142.207.149; Mon, 09 Mar 2009 15:08:39 -0700
Return-Path: <postmaster@yahoo.com>
Received: from 68.142.207.151  (HELO web32303.mail.mud.yahoo.com) (68.142.207.151)
  by mta156.mail.re4.yahoo.com with SMTP; Mon, 09 Mar 2009 15:08:39 -0700
Received: (qmail 46286 invoked by uid 60001); 9 Mar 2009 22:08:38 -0000
Message-ID: <747089.27380.qm@web32303.mail.mud.yahoo.com>
Received: from [209.131.62.113] by web32303.mail.mud.yahoo.com via HTTP; Mon, 09 Mar 2009 15:08:38 PDT
X-Mailer: Yahoo/1277.32 YahooService/0.7.289.8
Date: Mon, 9 Mar 2009 15:08:38 -0700 (PDT)
From: noreply <noreply@yahoo.com>
Reply-To: noreply <noreply@yahoo.com>
Subject: test attachment
To: test@yahoo.com
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-301986061-1236636518=:27380"
Content-Length: 746


--0-301986061-1236636518=:27380
Content-Type: multipart/alternative; boundary="0-365705378-1236636518=:27380"

--0-365705378-1236636518=:27380
Content-Type: text/plain; charset=us-ascii




      
--0-365705378-1236636518=:27380
Content-Type: text/html; charset=us-ascii

<html><head><style type="text/css"><!-- DIV {margin:0px;} --></style></head><body><div style="font-family:times new roman, new york, times, serif;font-size:12pt;color:#000000;"><DIV></DIV></div><br>

      </body></html>
--0-365705378-1236636518=:27380--
--0-301986061-1236636518=:27380
Content-Type: text/plain; name="testattach.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="testattach.txt"

dGVzdA==

--0-301986061-1236636518=:27380--
